# Run tests on Fedora and Ubuntu Docker images using GIFT CORP and GIFT PPA on commit
name: test_docker
on: [push]
permissions: read-all
jobs:
  test_fedora:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['38']
    container:
      image: registry.fedoraproject.org/fedora:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up container
      run: |
        dnf install -y dnf-plugins-core langpacks-en
    - name: Install dependencies
      run: |
        dnf install -y @development-tools python3 python3-devel python3-setuptools
    - name: Install dependencies
      env:
        LANG: C.utf8
      run: |
        python3 setup.py install
    - name: Run tests
      env:
        LANG: C.utf8
      run: |
        python3 ./run_tests.py
    - name: Run end-to-end tests
      run: |
        if test -f tests/end-to-end.py; then PYTHONPATH=. python3 ./tests/end-to-end.py --debug -c config/end-to-end.ini; fi
    - name: Build source distribution
      run: |
        python3 ./setup.py sdist
    - name: Build binary distribution
      run: |
        python3 ./setup.py bdist
    - name: Run build and install test
      run: |
        python3 ./setup.py build
        python3 ./setup.py install
  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['22.04']
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up container
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q
        apt-get install -y libterm-readline-gnu-perl locales software-properties-common git
        locale-gen en_US.UTF-8
        ln -f -s /usr/share/zoneinfo/UTC /etc/localtime
        git clone https://github.com/Schramp/UnifiedLogTestData.git
    - name: Install dependencies
      run: |
        apt-get update -q
        apt-get install -y build-essential python3 python3-dev python3-setuptools
    - name: Install dependencies
      env:
        LANG: C.utf8
      run: |
        python3 setup.py install
    - name: Run tests
      env:
        LANG: en_US.UTF-8
      run: |
        python3 ./run_tests.py
    - name: Build source distribution
      run: |
        python3 ./setup.py sdist
    - name: Build binary distribution
      run: |
        python3 ./setup.py bdist
    - name: Run build and install test
      run: |
        python3 ./setup.py build
        python3 ./setup.py install
